// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcHkzcc_iR3wx9VkfZ7oIhq70tyfM_-Ec',
    appId: '1:980319898640:web:ba354166c2286fbcfa8e95',
    messagingSenderId: '980319898640',
    projectId: 'adocao-animais-app',
    authDomain: 'adocao-animais-app.firebaseapp.com',
    storageBucket: 'adocao-animais-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtKPKWjKwR3ugO9TgpT9tWyUQuorxBANY',
    appId: '1:980319898640:android:d5156febaa8511e3fa8e95',
    messagingSenderId: '980319898640',
    projectId: 'adocao-animais-app',
    storageBucket: 'adocao-animais-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK1UooSKuHoYnLbKZI-s91U83FD8JIIGg',
    appId: '1:980319898640:ios:94e99956ff57d456fa8e95',
    messagingSenderId: '980319898640',
    projectId: 'adocao-animais-app',
    storageBucket: 'adocao-animais-app.firebasestorage.app',
    iosBundleId: 'com.example.pet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK1UooSKuHoYnLbKZI-s91U83FD8JIIGg',
    appId: '1:980319898640:ios:94e99956ff57d456fa8e95',
    messagingSenderId: '980319898640',
    projectId: 'adocao-animais-app',
    storageBucket: 'adocao-animais-app.firebasestorage.app',
    iosBundleId: 'com.example.pet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcHkzcc_iR3wx9VkfZ7oIhq70tyfM_-Ec',
    appId: '1:980319898640:web:e14135ce21dc82a4fa8e95',
    messagingSenderId: '980319898640',
    projectId: 'adocao-animais-app',
    authDomain: 'adocao-animais-app.firebaseapp.com',
    storageBucket: 'adocao-animais-app.firebasestorage.app',
  );
}
